var services = ["governor",
                "janitor",
                "stats",
                "log",
                "kv",
                "backIndex",
                "index",
                "index.fullText",
                "view",
                "proxy",
                "doctor",
                "autoFailOver",
                "xdcr",
                "backup"];
